---
- name: Pull Python image
  docker_image:
    name: python
    source: pull

- name: Run apt-get update
  docker_container:
    name: backend
    image: python
    state: started
    command: apt-get update

- name: Install Python and pip
  docker_container:
    name: backend
    image: python
    state: started
    command: apt-get install -y python3 python3-pip

- name: Create application directory
  file:
    path: /opt/backend
    state: directory

- name: Copy application files
  copy:
    src: files/
    dest: /opt/backend/

- name: Install dependencies
  docker_container:
    name: backend
    image: python
    state: started
    command: pip install -r /opt/backend/requirements.txt

