---
- name: Deploy Three-tier Application
  hosts: docker
  become: yes

  tasks:
    - name: Create temporary directory for Docker build
      file:
        path: /tmp/docker_build
        state: directory

    - name: Copy Dockerfile to the temporary directory
      copy:
        src: Dockerfile
        dest: /tmp/docker_build/Dockerfile

    - name: Build Docker image
      docker_image:
        name: three_tier_app
        source: build
        build:
          path: /tmp/docker_build
        tag: latest

    - name: Run Docker container
      docker_container:
        name: three_tier_container
        image: three_tier_app:latest
        ports:
          - "80:80"
          - "443:443"
        detach: yes

