---
- name: Pull Python image
  docker_image:
    name: python
    source: pull

- name: Stop and remove existing backend container
  docker_container:
    name: backend
    state: absent

- name: Create application directory
  file:
    path: /opt/backend
    state: directory

- name: Copy application files
  copy:
    src: files/
    dest: /opt/backend/

- name: Copy requirements file
  copy:
    src: files/requirements.txt
    dest: /opt/backend/

- name: Install Python and pip
  docker_container:
    name: backend
    image: python
    state: started
    command: /bin/bash -c "apt-get update && apt-get install -y python3 python3-pip && pip3 install --upgrade pip"

- name: Install dependencies
  docker_container:
    name: backend
    image: python
    state: started
    command: /bin/bash -c "pip3 install -r /opt/backend/requirements.txt"

