---
- name: Pull Nginx image
  docker_image:
    name: nginx
    source: pull

- name: Run Nginx container
  docker_container:
    name: frontend
    image: nginx
    state: started
    ports:
      - "80:{{ frontend_port }}"

